// packages/solid/src/lib/styled-cva/styled-cva.tsx
/* eslint-disable @typescript-eslint/no-explicit-any */

import {
  capitalize,
  cleanTemplate,
  cn,
  cva,
  mergeArrays,
  removeTransientProps,
  type VariantProps,
} from "@styled-cva/core";
import {
  createMemo,
  type Component,
  type JSX,
  type ValidComponent,
  mergeProps,
  splitProps,
} from "solid-js";
import { Dynamic } from "solid-js/web";

import domElements from "../../domElements";
import {
  isTwElement,
  type AnyTailwindComponent,
  type ElementKey,
  type IntrinsicElementsKeys,
  type IntrinsicElementsTemplateFunctionsMap,
  type TailwindInterface,
} from "./types";

const isTw = (c: any): c is AnyTailwindComponent => c[isTwElement] === true;

const templateFunctionFactory: TailwindInterface = (<
  C extends ValidComponent,
>(
  Element: C,
) => {
  return (
    template: TemplateStringsArray,
    ...templateElements: ((props: any) => string | undefined | null)[]
  ) => {
    const TwComponentConstructor = (
      styleArray: (JSX.CSSProperties | ((p: any) => JSX.CSSProperties))[] = [],
    ) => {
      const TwComponent = (baseProps: any): JSX.Element => {
        // Split out our special props from the rest
        const [local, props] = splitProps(baseProps, [
          "$as",
          "style",
          "class",
          "ref",
        ]);

        // Determine the final element to render - reactive
        const $as = createMemo(() => local.$as ?? Element);
        const FinalElement = createMemo(() =>
          isTw(Element) ? Element : $as(),
        );

        // Compute accumulated styles - reactive
        const withStyles = createMemo<JSX.CSSProperties>(() =>
          styleArray
            ? styleArray.reduce<JSX.CSSProperties>(
                (acc, intStyle) =>
                  Object.assign(
                    acc,
                    typeof intStyle === "function"
                      ? intStyle(baseProps)
                      : intStyle,
                  ),
                {} as JSX.CSSProperties,
              )
            : {},
        );

        // Filter out transient props (starting with "$") unless styling another Tw component
        // This needs to be reactive to respond to prop changes
        const filteredProps = createMemo(() =>
          isTw(FinalElement()) || typeof Element !== "string"
            ? props
            : (Object.fromEntries(
                Object.entries(props).filter(removeTransientProps),
              ) as any),
        );

        // Compute class names - reactive
        const computedClass = createMemo(() =>
          cleanTemplate(
            mergeArrays(
              template,
              templateElements.map((t) => t({ ...props, $as: $as() })),
            ),
            local.class ?? "",
          ),
        );

        // Merge styles - reactive
        const mergedStyle = createMemo(() =>
          typeof local.style === "object"
            ? { ...withStyles(), ...local.style }
            : withStyles(),
        );

        return (
          <Dynamic
            component={FinalElement()}
            {...filteredProps()}
            style={mergedStyle()}
            ref={local.ref}
            class={computedClass()}
            {...(isTw(Element) ? { $as: $as() } : {})}
          />
        );
      };

      // Symbol identifier for detecting tailwind-styled-components
      (TwComponent as any)[isTwElement] = true;

      // Display name for debugging
      if (typeof Element !== "string") {
        (TwComponent as any).displayName =
          (Element as any).displayName ||
          (Element as any).name ||
          "tw.Component";
      } else {
        (TwComponent as any).displayName = "tw." + Element;
      }

      // withStyle method for chaining
      (TwComponent as any).withStyle = (
        styles: ((p: any) => JSX.CSSProperties) | JSX.CSSProperties,
      ) => TwComponentConstructor(styleArray.concat(styles)) as any;

      return TwComponent;
    };

    return TwComponentConstructor();
  };
}) as any;

const intrinsicElementsMap = domElements.reduce(
  <K extends IntrinsicElementsKeys>(
    acc: IntrinsicElementsTemplateFunctionsMap,
    DomElement: K,
  ) => ({
    ...acc,
    [DomElement]: templateFunctionFactory(DomElement),
  }),
  {} as IntrinsicElementsTemplateFunctionsMap,
);

const tw: TailwindInterface = Object.assign(
  templateFunctionFactory,
  intrinsicElementsMap,
);

export default tw;

type CVA<T = unknown> = typeof cva;

type StyledExtension = {
  $as?: ElementKey | Component<any>;
};

// Type for valid withProps input: element props + data-* attributes + variant props
type ValidElementProps<K extends ElementKey> = {
  [P in keyof JSX.IntrinsicElements[K] as P extends `$${string}`
    ? never
    : P]?: JSX.IntrinsicElements[K][P];
};

// ValidWithProps includes element props, data attributes, and variant props
type ValidWithProps<K extends ElementKey, T> = ValidElementProps<K> & {
  [key: `data-${string}`]: string;
} & Partial<T>;

type CVAWithPropsReturn<K extends ElementKey, T> = Component<
  JSX.IntrinsicElements[K] & VariantProps<typeof cva> & StyledExtension
> & {
  /**
   * Sets default props for the component. User-provided props will override these defaults.
   *
   * @param defaultProps - An object containing default props to apply to the component.
   *                       Accepts known element props, data-* attributes, and variant props.
   *                       Variant prop values are validated against the variant definitions.
   * @returns A component with the default props applied
   *
   * @example
   * ```tsx
   * const StyledButton = tw.button.cva("btn-base", {
   *   variants: {
   *     $variant: {
   *       primary: "btn-primary",
   *       secondary: "btn-secondary",
   *     },
   *   },
   * }).withProps({
   *   'data-some-prop': 'some-value',
   *   type: 'button',
   *   $variant: 'primary' // Valid variant value
   * });
   *
   * // The component will have data-some-prop="some-value", type="button", and $variant="primary" by default
   * <StyledButton>Click me</StyledButton>
   * ```
   */
  withProps: <DefaultProps extends ValidWithProps<K, T>>(
    defaultProps: DefaultProps & {
      [P in Exclude<keyof DefaultProps, keyof ValidWithProps<K, T>>]?: never;
    },
  ) => Component<
    JSX.IntrinsicElements[K] & VariantProps<typeof cva> & StyledExtension
  >;
};

export type StyledCVA = TailwindInterface & {
  /**
   * A factory function that creates a styled component with variant props
   */
  [K in ElementKey]: TailwindInterface[K] & {
    /**
     * A factory function that creates a styled component with variant props
     *
     * @param args - a tuple containing the `cva` function arguments
     * @returns A styled component with variant props and a `.withProps()` method
     *
     * @example
     * ```tsx
     * const StyledButton = tw.button.cva("btn-base", {
     *  variants: {
     *  // variant keys starting with $ will not be sent to the DOM,
     *  // this avoids extraneous props warning
     *    $variant: {
     *      primary: "btn-primary",
     *      secondary: "btn-secondary",
     *    },
     *  }
     * });
     *
     * // ...
     *
     * <StyledButton $variant="primary">Click me</StyledButton>
     * ```
     */
    cva: <T>(...args: Parameters<CVA<T>>) => CVAWithPropsReturn<K, T>;
  };
};

export function createStyledCVA(): StyledCVA {
  const twCVA = Object.fromEntries(
    Object.entries(tw).map(([key, styledFn]) => [
      key,
      Object.assign(styledFn, {
        cva: (...args: Parameters<CVA>) => {
          const variance = cva(...args);

          type Props = VariantProps<typeof variance> & {
            class?: string;
            ref?: any;
          } & StyledExtension;

          const StyledComponent = styledFn`` as Component<Props>;

          const WithVariants: Component<Props> = (props) => {
            // Use createMemo to compute class reactively
            // Cast props to any to preserve Solid's reactivity proxy while satisfying CVA's type
            const computedClass = createMemo(() =>
              cn(variance(props as any), props.class),
            );

            return <StyledComponent {...props} class={computedClass()} />;
          };

          (WithVariants as any).displayName = `Styled${capitalize(key)}`;

          // Add withProps method to the component
          type ValidPropsForImplementation = ValidElementProps<any> & {
            [key: `data-${string}`]: string;
          } & Partial<VariantProps<typeof variance>>;

          const ComponentWithProps = WithVariants as typeof WithVariants & {
            withProps: <DefaultProps extends ValidPropsForImplementation>(
              defaultProps: DefaultProps,
            ) => Component<Props>;
          };

          ComponentWithProps.withProps = ((defaultProps: any) => {
            const ComponentWithDefaultProps: Component<Props> = (userProps) => {
              // Merge default props with user props (user props take precedence)
              const merged = mergeProps(defaultProps, userProps) as Props;
              return <WithVariants {...merged} />;
            };

            (ComponentWithDefaultProps as any).displayName = `${(WithVariants as any).displayName}.withProps`;

            return ComponentWithDefaultProps;
          }) as typeof ComponentWithProps.withProps;

          return ComponentWithProps;
        },
      }),
    ]),
  );

  return Object.assign(tw, twCVA) as StyledCVA;
}

// src/lib/styled-cva/styled-cva.tsx
/* eslint-disable @typescript-eslint/no-explicit-any */

import React, {
  forwardRef,
  type ComponentType,
  type CSSProperties,
  type FC,
} from "react";

import domElements from "../../domElements";
import { cn } from "../cn";
import { cva, type VariantProps } from "../cva";
import { capitalize } from "../utils";
import {
  isTwElement,
  type AnyTailwindComponent,
  type Interpolation,
  type IntrinsicElementsKeys,
  type IntrinsicElementsTemplateFunctionsMap,
  type Nullish,
  type TailwindInterface,
} from "./types";

export const mergeArrays = (
  template: TemplateStringsArray,
  templateElements: Array<Nullish<string>>,
) =>
  template.reduce<string[]>(
    (acc, c, i) => acc.concat(c || [], templateElements[i] || []), //  x || [] to remove false values e.g '', null, undefined. as Array.concat() ignores empty arrays i.e []
    [],
  );

export function cleanTemplate(
  template: Array<Interpolation<any>>,
  inheritedClasses: string = "",
) {
  const newClasses = template
    .join(" ")
    .trim()
    .replace(/\n/g, " ") // replace newline with space
    .replace(/\s{2,}/g, " ") // replace multiple spaces with single space
    .split(" ")
    .filter((c) => c !== ","); // remove comma introduced by template to string

  const inheritedClassesArray = inheritedClasses
    ? inheritedClasses.split(" ")
    : [];

  return cn(
    ...newClasses
      .concat(inheritedClassesArray) // add new classes to inherited classes
      .filter((c: string) => c !== " "), // remove empty classes
  );
}

/**
 * A utility function that strips out transient props from a [key,value] array of props
 *
 * @param {[string, any]} [key]
 * @return boolean
 */
const removeTransientProps = ([key]: [string, any]): boolean =>
  key.charAt(0) !== "$";

const isTw = (c: any): c is AnyTailwindComponent => c[isTwElement] === true;

const templateFunctionFactory: TailwindInterface = (<
  C extends React.ElementType,
>(
  Element: C,
) => {
  return (
    template: TemplateStringsArray,
    ...templateElements: ((props: any) => string | undefined | null)[]
  ) => {
    const TwComponentConstructor = (
      styleArray: (CSSProperties | ((p: any) => CSSProperties))[] = [],
    ) => {
      const TwComponent = React.forwardRef(
        (baseProps: any, ref: any): JSX.Element => {
          const { $as = Element, style = {}, ...props } = baseProps;

          // set FinalElement based on if Element is a TailwindComponent, $as defaults to Element if undefined
          const FinalElement = isTw(Element) ? Element : $as;

          const withStyles: CSSProperties = styleArray
            ? styleArray.reduce<CSSProperties>(
                (acc, intStyle) =>
                  Object.assign(
                    acc,
                    typeof intStyle === "function"
                      ? intStyle(baseProps)
                      : intStyle,
                  ),
                {} as CSSProperties,
              )
            : {};

          // filter out props that starts with "$" props except when styling a tailwind-styled-component
          const filteredProps =
            isTw(FinalElement) || typeof Element !== "string"
              ? props
              : (Object.fromEntries(
                  Object.entries(props).filter(removeTransientProps),
                ) as any);

          return (
            <FinalElement
              // forward props
              {...filteredProps}
              style={{ ...withStyles, ...style }}
              // forward ref
              ref={ref}
              // set class names
              className={cleanTemplate(
                mergeArrays(
                  template,
                  templateElements.map((t) => t({ ...props, $as })),
                ),
                props.className,
              )}
              // forward $as prop when styling a tailwind-styled-component
              {...(isTw(Element) ? { $as } : {})}
            />
          );
        },
      ) as any;
      // symbol identifier for detecting tailwind-styled-components
      TwComponent[isTwElement] = true;
      // This enables the react tree to show a name in devtools, much better debugging experience Note: Far from perfect, better implementations welcome
      if (typeof Element !== "string") {
        TwComponent.displayName =
          (Element as any).displayName ||
          (Element as any).name ||
          "tw.Component";
      } else {
        TwComponent.displayName = "tw." + Element;
      }
      TwComponent.withStyle = (
        styles: ((p: any) => CSSProperties) | CSSProperties,
      ) => TwComponentConstructor(styleArray.concat(styles)) as any;

      return TwComponent;
    };
    return TwComponentConstructor();
  };
}) as any;

const intrinsicElementsMap: IntrinsicElementsTemplateFunctionsMap =
  domElements.reduce(
    <K extends IntrinsicElementsKeys>(
      acc: IntrinsicElementsTemplateFunctionsMap,
      DomElement: K,
    ) => ({
      ...acc,
      [DomElement]: templateFunctionFactory(DomElement),
    }),
    {} as IntrinsicElementsTemplateFunctionsMap,
  );

const tw: TailwindInterface = Object.assign(
  templateFunctionFactory,
  intrinsicElementsMap,
);

export default tw;

type ElementKey = keyof TailwindInterface;

type CVA<T = unknown> = typeof cva<T>;

type StyledExtension = {
  $as?: ElementKey | ComponentType<any>;
};

export type StyledCVA = TailwindInterface & {
  /**
   * A factory function that creates a styled component with variant props
   */
  [K in ElementKey]: TailwindInterface[K] & {
    /**
     * A factory function that creates a styled component with variant props
     *
     * @param args - a tuple containing the `cva` function arguments
     * @returns A styled component with variant props
     *
     * @example
     * ```tsx
     * const StyledButton = tw.button.cva("btn-base", {
     *  variants: {
     *  // variant keys starting with $ will not be sent to the DOM,
     *  // this avoids extraneous props warning
     *    $variant: {
     *      primary: "btn-primary",
     *      secondary: "btn-secondary",
     *    },
     *  }
     * });
     *
     * // ...
     *
     * <StyledButton $variant="primary">Click me</StyledButton>
     * ```
     */
    cva: <T>(
      ...args: Parameters<CVA<T>>
    ) => FC<
      JSX.IntrinsicElements[K] &
        VariantProps<ReturnType<CVA<T>>> &
        StyledExtension
    >;
  };
};

export function createStyledCVA(): StyledCVA {
  const twCVA = Object.fromEntries(
    Object.entries(tw).map(([key, styledFn]) => [
      key,
      Object.assign(styledFn, {
        cva: (...args: Parameters<CVA>) => {
          const variance = cva(...args);

          type Props = VariantProps<typeof variance> & {
            className?: string;
            ref?: React.Ref<HTMLElement>;
          } & StyledExtension;

          const StyledComponent = styledFn`` as FC<Props>;

          const WithRef = forwardRef<HTMLElement, Props>(
            ({ className, ...props }, ref) => (
              <StyledComponent
                className={cn(variance({ ...props, className }), className)}
                {...props}
                ref={ref}
              />
            ),
          );

          WithRef.displayName = `Styled${capitalize(key)}`;

          return WithRef;
        },
      }),
    ]),
  );

  return Object.assign(tw, twCVA) as StyledCVA;
}
