// packages/solid/src/lib/styled-cva/styled-cva.tsx
/* eslint-disable @typescript-eslint/no-explicit-any */

import {
  capitalize,
  cleanTemplate,
  cn,
  cva,
  isTaggedTemplateArg,
  mergeArrays,
  removeTransientProps,
  type VariantProps,
} from "@styled-cva/core";
import {
  createMemo,
  mergeProps,
  splitProps,
  type Component,
  type JSX,
  type ValidComponent,
} from "solid-js";
import { Dynamic } from "solid-js/web";

import domElements from "../../domElements";
import {
  isTwElement,
  type AnyTailwindComponent,
  type ElementKey,
  type IntrinsicElementsKeys,
  type IntrinsicElementsTemplateFunctionsMap,
  type IsTwElement,
  type TailwindComponent,
  type TailwindInterface,
} from "./types";

const isTw = (c: any): c is AnyTailwindComponent => c[isTwElement] === true;

const templateFunctionFactory: TailwindInterface = (<C extends ValidComponent>(
  Element: C,
) => {
  return (
    template: TemplateStringsArray,
    ...templateElements: ((props: any) => string | undefined | null)[]
  ) => {
    const TwComponentConstructor = (
      styleArray: (JSX.CSSProperties | ((p: any) => JSX.CSSProperties))[] = [],
    ) => {
      const TwComponent = (baseProps: any): JSX.Element => {
        // Split out our special props from the rest
        const [local, props] = splitProps(baseProps, [
          "$as",
          "style",
          "class",
          "ref",
        ]);

        // Determine the final element to render - reactive
        const $as = createMemo(() => local.$as ?? Element);
        const FinalElement = createMemo(() =>
          isTw(Element) ? Element : $as(),
        );

        // Compute accumulated styles - reactive
        const withStyles = createMemo<JSX.CSSProperties>(() =>
          styleArray
            ? styleArray.reduce<JSX.CSSProperties>(
                (acc, intStyle) =>
                  Object.assign(
                    acc,
                    typeof intStyle === "function"
                      ? intStyle(baseProps)
                      : intStyle,
                  ),
                {} as JSX.CSSProperties,
              )
            : {},
        );

        // Filter out transient props (starting with "$") unless styling another Tw component
        // This needs to be reactive to respond to prop changes
        const filteredProps = createMemo(() =>
          isTw(FinalElement()) || typeof Element !== "string"
            ? props
            : (Object.fromEntries(
                Object.entries(props).filter(removeTransientProps),
              ) as any),
        );

        // Compute class names - reactive
        const computedClass = createMemo(() =>
          cleanTemplate(
            mergeArrays(
              template,
              templateElements.map((t) => t({ ...props, $as: $as() })),
            ),
            local.class ?? "",
          ),
        );

        // Merge styles - reactive
        const mergedStyle = createMemo(() =>
          typeof local.style === "object"
            ? { ...withStyles(), ...local.style }
            : withStyles(),
        );

        return (
          <Dynamic
            component={FinalElement()}
            {...filteredProps()}
            style={mergedStyle()}
            ref={local.ref}
            class={computedClass()}
            {...(isTw(Element) ? { $as: $as() } : {})}
          />
        );
      };

      // Symbol identifier for detecting tailwind-styled-components
      (TwComponent as any)[isTwElement] = true;

      // Display name for debugging
      if (typeof Element !== "string") {
        (TwComponent as any).displayName =
          (Element as any).displayName ||
          (Element as any).name ||
          "tw.Component";
      } else {
        (TwComponent as any).displayName = "tw." + Element;
      }

      // withStyle method for chaining
      (TwComponent as any).withStyle = (
        styles: ((p: any) => JSX.CSSProperties) | JSX.CSSProperties,
      ) => TwComponentConstructor(styleArray.concat(styles)) as any;

      return TwComponent;
    };

    return TwComponentConstructor();
  };
}) as any;

const intrinsicElementsMap = domElements.reduce(
  <K extends IntrinsicElementsKeys>(
    acc: IntrinsicElementsTemplateFunctionsMap,
    DomElement: K,
  ) => ({
    ...acc,
    [DomElement]: templateFunctionFactory(DomElement),
  }),
  {} as IntrinsicElementsTemplateFunctionsMap,
);

const tw: TailwindInterface = Object.assign(
  templateFunctionFactory,
  intrinsicElementsMap,
);

export default tw;

type CVA<T = unknown> = typeof cva<T>;

type StyledExtension = {
  $as?: ElementKey | Component<any>;
};

// Type for valid withProps input: element props + data-* attributes + variant props
type ValidElementProps<K extends ElementKey> = {
  [P in keyof JSX.IntrinsicElements[K] as P extends `$${string}`
    ? never
    : P]?: JSX.IntrinsicElements[K][P];
};

// ValidWithProps includes element props, data attributes, and variant props
type ValidWithProps<K extends ElementKey, T> = ValidElementProps<K> & {
  [key: `data-${string}`]: string;
} & Partial<VariantProps<ReturnType<CVA<T>>>>;

// Polymorphic props when $as is used: accept the "as" element's props (e.g. href when $as="a")
type PolymorphicCVAProps<
  T,
  $As extends ElementKey,
> = JSX.IntrinsicElements[$As] &
  VariantProps<ReturnType<CVA<T>>> &
  StyledExtension & { $as?: $As };

// CVA component props (element + variant + $as); used so tw(CVAComponent) preserves $variant, $size, etc.
type CVAProps<K extends ElementKey, T> = JSX.IntrinsicElements[K] &
  VariantProps<ReturnType<CVA<T>>> &
  StyledExtension;

// Use `object` (not `Record<string, unknown>`) for the second TailwindComponent
// generic: `Record<string, unknown>` adds an index signature, which widens
// `keyof` inside TailwindPropHelper and collapses variant literal unions
// (e.g. `$variant: "primary" | "secondary"`) to `string` at the JSX call site.
type CVAWithPropsReturn<K extends ElementKey, T> = TailwindComponent<
  CVAProps<K, T>,
  object
> &
  IsTwElement &
  Component<CVAProps<K, T>> & {
    <$As extends ElementKey>(props: PolymorphicCVAProps<T, $As>): JSX.Element;
    /**
     * Sets default props for the component. User-provided props will override these defaults.
     *
     * @param defaultProps - An object containing default props to apply to the component.
     *                       Accepts known element props, data-* attributes, and variant props.
     *                       Variant prop values are validated against the variant definitions.
     * @returns A component with the default props applied
     *
     * @example
     * ```tsx
     * const StyledButton = tw.button.cva("btn-base", {
     *   variants: {
     *     $variant: {
     *       primary: "btn-primary",
     *       secondary: "btn-secondary",
     *     },
     *   },
     * }).withProps({
     *   'data-some-prop': 'some-value',
     *   type: 'button',
     *   $variant: 'primary' // Valid variant value
     * });
     *
     * // The component will have data-some-prop="some-value", type="button", and $variant="primary" by default
     * <StyledButton>Click me</StyledButton>
     * ```
     */
    withProps: <DefaultProps extends ValidWithProps<K, T>>(
      defaultProps: DefaultProps & {
        [P in Exclude<keyof DefaultProps, keyof ValidWithProps<K, T>>]?: never;
      },
    ) => Component<CVAProps<K, T>>;
  };

/** Intrinsic CVA: `tw.button(base, config)` — preferred over `.cva(base, config)`. */

type IntrinsicCVAShorthand<K extends ElementKey> = <T>(
  ...args: Parameters<CVA<T>>
) => CVAWithPropsReturn<K, T>;

export type StyledCVA = TailwindInterface & {
  [K in ElementKey]: TailwindInterface[K] & {
    /**
     * @deprecated Prefer intrinsic CVA shorthand — call `tw.button(base, config)` instead of
     * `tw.button.cva(base, config)` (same types and runtime).
     *
     * @param args - `cva` arguments (`base` classes + config)
     * @returns A styled component with variant props and `.withProps()`
     *
     * @example Shorthand (preferred)
     * ```tsx
     * const StyledButton = tw.button("btn-base", {
     *   variants: {
     *     $variant: { primary: "btn-primary", secondary: "btn-secondary" },
     *   },
     * });
     * ```
     */
    cva: <T>(...args: Parameters<CVA<T>>) => CVAWithPropsReturn<K, T>;
  } & IntrinsicCVAShorthand<K>;
};

export function createStyledCVA(): StyledCVA {
  const twCVA = Object.fromEntries(
    Object.entries(tw).map(([key, styledFn]) => {
      const cvaImpl = (...args: Parameters<CVA>) => {
        const variance = cva(...args);

        type Props = VariantProps<typeof variance> & {
          class?: string;
          ref?: any;
        } & StyledExtension;

        const StyledComponent = styledFn`` as Component<Props>;

        const WithVariants: Component<Props> = (props) => {
          // Use createMemo to compute class reactively
          // Cast props to any to preserve Solid's reactivity proxy while satisfying CVA's type
          const computedClass = createMemo(() =>
            cn(variance(props as any), props.class),
          );

          return <StyledComponent {...props} class={computedClass()} />;
        };

        (WithVariants as any).displayName = `Styled${capitalize(key)}`;

        // Add withProps method to the component
        type ValidPropsForImplementation = ValidElementProps<any> & {
          [key: `data-${string}`]: string;
        } & Partial<VariantProps<typeof variance>>;

        const ComponentWithProps = WithVariants as typeof WithVariants & {
          withProps: <DefaultProps extends ValidPropsForImplementation>(
            defaultProps: DefaultProps,
          ) => Component<Props>;
        };

        ComponentWithProps.withProps = ((defaultProps: any) => {
          const ComponentWithDefaultProps: Component<Props> = (userProps) => {
            // Merge default props with user props (user props take precedence)
            const merged = mergeProps(defaultProps, userProps) as Props;
            return <WithVariants {...merged} />;
          };

          (ComponentWithDefaultProps as any).displayName =
            `${(WithVariants as any).displayName}.withProps`;

          return ComponentWithDefaultProps;
        }) as typeof ComponentWithProps.withProps;

        return ComponentWithProps;
      };

      const wrapped = function (this: unknown, ...args: unknown[]) {
        if (isTaggedTemplateArg(args[0])) {
          return (styledFn as (...a: unknown[]) => unknown).apply(this, args);
        }
        return cvaImpl(...(args as Parameters<CVA>));
      };

      Object.assign(wrapped, styledFn, { cva: cvaImpl });

      return [key, wrapped];
    }),
  );

  return Object.assign(tw, twCVA) as unknown as StyledCVA;
}

// src/styled-cva.tsx
/* eslint-disable @typescript-eslint/ban-types */
/* eslint-disable @typescript-eslint/no-explicit-any */

import React, {
  forwardRef,
  type CSSProperties,
  type ComponentType,
  type FC,
} from "react";

import { cva, type VariantProps } from "class-variance-authority";

import { capitalize, cn } from "./utils";
import domElements from "./domElements";

const isTwElement = Symbol("isTwElement?");

export type Nullish<T> = T | null | undefined;
export type IsTwElement = { [isTwElement]: true };
export type FalseyValue = undefined | null | false;

export type FlattenInterpolation<P> = ReadonlyArray<Interpolation<P>>;
export type InterpolationValue =
  | string
  | number
  | FalseyValue
  | TailwindComponentInterpolation;

export type Interpolation<P> =
  | InterpolationValue
  | InterpolationFunction<P>
  | FlattenInterpolation<P>;

export type InterpolationFunction<P> = (props: P) => Interpolation<P>;

type TailwindComponentInterpolation = Pick<
  TailwindComponentBase<any, any>,
  keyof TailwindComponentBase<any, any>
>;

type IntrinsicElementsKeys = keyof JSX.IntrinsicElements;

type IsAny<T, True, False = never> = True | False extends (
  T extends never ? True : False
)
  ? True
  : False;

export const mergeArrays = (
  template: TemplateStringsArray,
  templateElements: Array<Nullish<string>>
) =>
  template.reduce<string[]>(
    (acc, c, i) => acc.concat(c || [], templateElements[i] || []), //  x || [] to remove false values e.g '', null, undefined. as Array.concat() ignores empty arrays i.e []
    []
  );

export function cleanTemplate(
  template: Array<Interpolation<any>>,
  inheritedClasses: string = ""
) {
  const newClasses = template
    .join(" ")
    .trim()
    .replace(/\n/g, " ") // replace newline with space
    .replace(/\s{2,}/g, " ") // replace multiple spaces with single space
    .split(" ")
    .filter((c) => c !== ","); // remove comma introduced by template to string

  const inheritedClassesArray = inheritedClasses
    ? inheritedClasses.split(" ")
    : [];

  return cn(
    ...newClasses
      .concat(inheritedClassesArray) // add new classes to inherited classes
      .filter((c: string) => c !== " ") // remove empty classes
  );
}

export type RemoveIndex<T> = {
  [K in keyof T as string extends K
    ? never
    : number extends K
    ? never
    : K]: T[K];
};

/**
 * ForwardRef typings
 */
export type TailwindExoticComponent<P> = Pick<
  React.ForwardRefExoticComponent<P>,
  keyof React.ForwardRefExoticComponent<any>
>;

type MergeProps<O extends object, P extends {} = {}> =
  // Distribute unions early to avoid quadratic expansion
  P extends any ? IsAny<P, RemoveIndex<P> & O, P & O> : never;
// RemoveIndex<P> is used to make React.ComponentPropsWithRef typesafe on Tailwind components, delete if causing issues

type TailwindPropHelper<
  P extends {},
  O extends object = {}
  // Pick is needed here to make $as typing work
> = Pick<MergeProps<O, P>, keyof MergeProps<O, P>>;

type TailwindComponentPropsWith$As<
  P extends object,
  O extends object,
  $As extends string | React.ComponentType<any> = React.ComponentType<P>,
  P2 extends {} = $As extends AnyTailwindComponent
    ? TailwindComponentAllInnerProps<$As>
    : $As extends IntrinsicElementsKeys | React.ComponentType<any>
    ? React.ComponentPropsWithRef<$As>
    : never
> = P & O & TailwindPropHelper<P2> & { $as?: $As };

/**
 * An interface represent a component styled by tailwind-styled-components
 *
 * @export
 * @interface TailwindComponent
 * @template P The base react props
 * @template O The props added with the template function.
 */
export type TailwindComponent<
  P extends object,
  O extends object = {}
> = IsTwElement & TailwindComponentBase<P, O> & WithStyle<P, O>;

/**
 * An interface represent a component styled by tailwind-styled-components
 *
 * @export
 * @interface TailwindComponentBase
 * @extends {TailwindExoticComponent<TailwindPropHelper<P, O>>}
 * @template P The base react props
 * @template O The props added with the template function.
 */
export interface TailwindComponentBase<P extends object, O extends object = {}>
  extends TailwindExoticComponent<TailwindPropHelper<P, O>> {
  // add our own fake call signature to implement the polymorphic '$as' prop
  (
    props: TailwindPropHelper<P, O> & { $as?: never | undefined }
  ): React.ReactElement<TailwindPropHelper<P, O>>;

  <$As extends string | React.ComponentType<any> = React.ComponentType<P>>(
    props: TailwindComponentPropsWith$As<P, O, $As>
  ): React.ReactElement<TailwindComponentPropsWith$As<P, O, $As>>;
}
/**
 *  An interface represent withStyle functionality
 *
 * @export
 * @interface WithStyle
 * @template P
 * @template O
 */
export interface WithStyle<P extends object, O extends object = {}> {
  withStyle: <S extends object = {}>(
    styles: CSSProperties | ((p: P & O & S) => CSSProperties)
  ) => TailwindComponent<P, O & S>;
}
/**
 * Generice TailwindComponent
 */
type AnyTailwindComponent = TailwindComponent<any, any>;

/**
 * A template function that accepts a template literal of tailwind classes and returns a tailwind-styled-component
 *
 * @export
 * @interface TemplateFunction
 * @template E
 */
export interface TemplateFunction<P extends object, O extends object = {}> {
  (template: TemplateStringsArray): TailwindComponent<P, O>;
  (
    template: TemplateStringsArray | InterpolationFunction<P & O>,
    ...rest: Array<Interpolation<P & O>>
  ): TailwindComponent<P, O>;
  <K extends object>(
    template: TemplateStringsArray | InterpolationFunction<P & O & K>,
    ...rest: Array<Interpolation<P & O & K>>
  ): TailwindComponent<P, O & K>;
}

/**
 * A utility function that strips out transient props from a [key,value] array of props
 *
 * @param {[string, any]} [key]
 * @return boolean
 */
const removeTransientProps = ([key]: [string, any]): boolean =>
  key.charAt(0) !== "$";

export type TailwindComponentInnerProps<C extends AnyTailwindComponent> =
  C extends TailwindComponent<infer P, any> ? P : never;

export type TailwindComponentInnerOtherProps<C extends AnyTailwindComponent> =
  C extends TailwindComponent<any, infer O> ? O : never;

export type TailwindComponentAllInnerProps<C extends AnyTailwindComponent> =
  TailwindComponentInnerProps<C> & TailwindComponentInnerOtherProps<C>;

export type IntrinsicElementsTemplateFunctionsMap = {
  [RTag in keyof JSX.IntrinsicElements]: TemplateFunction<
    JSX.IntrinsicElements[RTag]
  >;
};

export interface TailwindInterface
  extends IntrinsicElementsTemplateFunctionsMap {
  <C extends TailwindComponent<any, any>>(component: C): TemplateFunction<
    TailwindComponentInnerProps<C>,
    TailwindComponentInnerOtherProps<C>
  >;
  <C extends React.ComponentType<any>>(component: C): TemplateFunction<
    // Prevent functional components without props infering props as `unknown`
    C extends (P?: never) => any ? {} : React.ComponentPropsWithoutRef<C>
  >;

  <C extends keyof JSX.IntrinsicElements>(component: C): TemplateFunction<
    JSX.IntrinsicElements[C]
  >;
}

const isTw = (c: any): c is AnyTailwindComponent => c[isTwElement] === true;

const templateFunctionFactory: TailwindInterface = (<
  C extends React.ElementType
>(
  Element: C
): any => {
  return (
    template: TemplateStringsArray,
    ...templateElements: ((props: any) => string | undefined | null)[]
  ) => {
    const TwComponentConstructor = (
      styleArray: (CSSProperties | ((p: any) => CSSProperties))[] = []
    ) => {
      const TwComponent = React.forwardRef(
        (baseProps: any, ref: any): JSX.Element => {
          const { $as = Element, style = {}, ...props } = baseProps;

          // set FinalElement based on if Element is a TailwindComponent, $as defaults to Element if undefined
          const FinalElement = isTw(Element) ? Element : $as;

          const withStyles: CSSProperties = styleArray
            ? styleArray.reduce<CSSProperties>(
                (acc, intStyle) =>
                  Object.assign(
                    acc,
                    typeof intStyle === "function"
                      ? intStyle(baseProps)
                      : intStyle
                  ),
                {} as CSSProperties
              )
            : {};

          // filter out props that starts with "$" props except when styling a tailwind-styled-component
          const filteredProps = isTw(FinalElement)
            ? props
            : (Object.fromEntries(
                Object.entries(props).filter(removeTransientProps)
              ) as any);
          return (
            <FinalElement
              // forward props
              {...filteredProps}
              style={{ ...withStyles, ...style }}
              // forward ref
              ref={ref}
              // set class names
              className={cleanTemplate(
                mergeArrays(
                  template,
                  templateElements.map((t) => t({ ...props, $as }))
                ),
                props.className
              )}
              // forward $as prop when styling a tailwind-styled-component
              {...(isTw(Element) ? { $as } : {})}
            />
          );
        }
      ) as any;
      // symbol identifier for detecting tailwind-styled-components
      TwComponent[isTwElement] = true;
      // This enables the react tree to show a name in devtools, much better debugging experience Note: Far from perfect, better implementations welcome
      if (typeof Element !== "string") {
        TwComponent.displayName =
          (Element as any).displayName ||
          (Element as any).name ||
          "tw.Component";
      } else {
        TwComponent.displayName = "tw." + Element;
      }
      TwComponent.withStyle = (
        styles: ((p: any) => CSSProperties) | CSSProperties
      ) => TwComponentConstructor(styleArray.concat(styles)) as any;

      return TwComponent;
    };
    return TwComponentConstructor();
  };
}) as any;

const intrinsicElementsMap: IntrinsicElementsTemplateFunctionsMap =
  domElements.reduce(
    <K extends IntrinsicElementsKeys>(
      acc: IntrinsicElementsTemplateFunctionsMap,
      DomElement: K
    ) => ({
      ...acc,
      [DomElement]: templateFunctionFactory(DomElement),
    }),
    {} as IntrinsicElementsTemplateFunctionsMap
  );

const tw: TailwindInterface = Object.assign(
  templateFunctionFactory,
  intrinsicElementsMap
);

export default tw;

type ElementKey = keyof TailwindInterface;

type CVA<T = unknown> = typeof cva<T>;

type StyledExtension = {
  $as?: ElementKey | ComponentType<any>;
};

export type StyledCVA = TailwindInterface & {
  [K in ElementKey]: TailwindInterface[K] & {
    cva: <T>(
      ...args: Parameters<CVA<T>>
    ) => FC<
      JSX.IntrinsicElements[K] &
        VariantProps<ReturnType<CVA<T>>> &
        StyledExtension
    >;
  };
};

export function createStyledCVA(): StyledCVA {
  const twCVA = Object.fromEntries(
    Object.entries(tw).map(([key, styledFn]) => [
      key,
      Object.assign(styledFn, {
        cva: (...args: Parameters<CVA>) => {
          const variance = cva(...args);

          type Props = VariantProps<typeof variance> & {
            className?: string;
            ref?: React.Ref<HTMLElement>;
          } & StyledExtension;

          const StyledComponent = styledFn`` as FC<Props>;

          const WithRef = forwardRef<HTMLElement, Props>(
            ({ className, ...props }, ref) => (
              <StyledComponent
                className={cn(variance({ ...props, className }), className)}
                {...props}
                ref={ref}
              />
            )
          );

          WithRef.displayName = `Styled${capitalize(key)}`;

          return WithRef;
        },
      }),
    ])
  );

  return Object.assign(tw, twCVA) as StyledCVA;
}
